### ISSUE TITLE
Error with Add Column functionality 

### ISSUE THREAD

**Issue by nidhik157** [cscan/vue3-excel-editor#21]
```
runtime-core.esm-bundler.js:220 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at getStyleVal (VueExcelEditor.vue:1512:16)
    at Proxy.colSepMouseDown (VueExcelEditor.vue:1519:11)
    at _createElementVNode.onMousedown._cache.<computed>._cache.<computed> (VueExcelEditor.vue:59:33)
  
[Screencast from 05-02-23 07:03:13 PM IST.webm](https://user-images.githubusercontent.com/42907447/216822215-ecd54f49-405c-4fdf-8f32-dd317c9c4ed6.webm)

```

**Comment by nidhik157** [comment]
![Screenshot from 2023-02-05 19-05-44](https://user-images.githubusercontent.com/42907447/216822288-37c6d0b5-45c1-4ea2-988b-3254f93dec38.png)

**Comment by nidhik157** [comment]
@cscan FYI. This happens when I click on the add button for adding a new column

**Comment by cscan** [comment]
You may try the register hook:

```
<vue-excel-editor ref="editor" v-model="table" :register="regColumn" />

methods: {
   doImport () {
      this.$refs.editor.reset()
      this.table = [
         {columnA: 1, columnB: 992},
         {columnA: 2, columnB: 993},
         {columnA: 3, columnB: 994},
         {columnA: 4, columnB: 999}
      ],
   },
   regColumn (field, pos) {
      if (field.name === 'columnA') {
         field.width = '100px'
         field.dataType = 'NUMBER'
      }
      if (field.name === 'columnB') {
         field.width = '200px'
         field.dataType = 'NUMBER'
      }
   }
}
```
